module.exports ={
    es:{
        method: "Método",
        route: "Ruta",
        routes: "Rutas",
        auth: "Auth",
        description: "Descripción",
        tags: "Tags",
        request: "Parámetros",
        response: "Respuesta",
        data: "Datos",
        headers: "Cabeceras",
        name: "Nombre",
        type: "Tipo",
        rules: "Reglas",
        in: "En",
        example: "Ejemplo",
        models: "Modelos"
    },
    en:{
        method: "Method",
        route: "Route",
        routes: "Routes",
        auth: "Auth",
        description: "Description",
        tags: "Tags",
        request: "Request",
        response: "Response",
        data: "Data",
        headers: "Headers",
        name: "Name",
        type: "Type",
        rules: "Rules",
        in: "In",
        example: "Example",
        models: "Models",
    }
}